### ISSUE TITLE
Have you tried `set-window-option -g xterm-keys on` in tmux?

### ISSUE THREAD

**Issue by sorsasampo** [bendikro/emacs-conf#1]
Instead of this:

https://github.com/bendikro/emacs-conf/blob/259d90d083ec54e8a16c61b39abf5909b1b6e1df/emacs-conf/key-bindings.el#L46-L58

**Comment by bendikro** [comment]
@sorsasampo 
Sorry for the late reply, but I didn't see it until now.

I seems I did already have `xterm-keys on` set in [configs/tmux/tmux.conf#L34](https://github.com/bendikro/emacs-conf/blob/259d90d083ec54e8a16c61b39abf5909b1b6e1df/configs/tmux/tmux.conf#L34) and when I test setting `xterm-keys off`, the CTRL+arrow keys in emacs inside tmux no longer work. Setting the keys manually was necessary at one time, but it's 7 years ago I initially commited the original lines, so it seems they're no longer necessary.

Thanks anyways :-)
